### ISSUE TITLE
Meet errors when work with storm1.1.0+kafka0.10.2.1

### ISSUE THREAD

**Issue by amilyalways** [cestella/streaming_outliers#1]
I am trying to run your projects on my own storm cluster. However, I meet some problems and can not solve it. Can you give me a help?

My problem is published on the website _stackoverflow_. 

[Storm1.1.0 + kafka0.10.2.1: NoSuchMethodError&ExceptionInInitializerError](https://stackoverflow.com/questions/44557801/storm1-1-0-kafka0-10-2-1-nosuchmethoderrorexceptionininitializererror)

**Comment by amilyalways** [comment]
The problems have been solved. The reason of the problem is the version of jar is incompatible with the cluster. However, it still can not work. There is no error in storm worker's log, but the spout can not emit data...
